const TOKEN_ERRORS = {
  EXPIRED: 'TOKEN_EXPIRED',
  INVALID: 'TOKEN_INVALID',
  MISSING: 'TOKEN_MISSING',
  REVOKED: 'TOKEN_REVOKED',
};

const AUTH_ERRORS = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
};

const OAUTH_PROVIDERS = {
  GOOGLE: 'google',
  GITHUB: 'github',
};

const MAX_FAILED_ATTEMPTS = 5;
const LOCKOUT_DURATION_MINUTES = 30;
const PASSWORD_RESET_EXPIRY_HOURS = 1;
const EMAIL_VERIFY_EXPIRY_HOURS = 24;

module.exports = {
  TOKEN_ERRORS,
  AUTH_ERRORS,
  OAUTH_PROVIDERS,
  MAX_FAILED_ATTEMPTS,
  LOCKOUT_DURATION_MINUTES,
  PASSWORD_RESET_EXPIRY_HOURS,
  EMAIL_VERIFY_EXPIRY_HOURS,
};
